### ISSUE TITLE
Edit Getting Started Page

### ISSUE THREAD

**Issue by yamiha** [Pi4J/pi4j-example-fxgl#3]
- [ ] Go through the Getting Started Pages with Pi4J
- [ ]  Make Adjustments if necessary
- [ ] Add Images
- [ ] Hugo Learning
- [ ] Add Picade to "Introduction to electronics"

**Comment by yamiha** [comment]
realised that i need to study Hugo in order to adjust the pi4j.github.io pages, therefore added Hugo learning task

**Comment by FDelporte** [comment]
FYI the /docs/ directory of the website repository should not be touched, that one is auto-created by a GitHub Actions job and copied to the website.

**Comment by yamiha** [comment]
> FYI the /docs/ directory of the website repository should not be touched, that one is auto-created by a GitHub Actions job and copied to the website.

okay thank you Frank i will take note :)
